/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 frontend/components/models/crown/crown.glb --transform --types
*/
"use client";

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ToonMaterial } from "../../materials/ToonMaterial";

type GLTFResult = GLTF & {
  nodes: {
    Circle032: THREE.Mesh;
    Circle032_1: THREE.Mesh;
  };
  materials: {
    ["Premium Golden"]: THREE.MeshStandardMaterial;
    ["Color - Gem"]: THREE.MeshPhysicalMaterial;
  };
};

export function Crown(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/crown-transformed.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Circle009" position={[0, -0.63, -0.06]}>
          <mesh
            name="Circle032"
            geometry={nodes.Circle032.geometry}
            // material={materials["Premium Golden"]}
          >
            <ToonMaterial color="#bf8221" />
          </mesh>
          <mesh
            name="Circle032_1"
            geometry={nodes.Circle032_1.geometry}
            // material={materials["Color - Gem"]}
          >
            <ToonMaterial color="#8c0303" />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/crown-transformed.glb");
