/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 frontend/components/models/gear/setting.glb --transform --types
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ToonMaterial } from "../../materials/ToonMaterial";

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh;
  };
  materials: {
    ["Color - Red"]: THREE.MeshStandardMaterial;
  };
};

export function Gear(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/setting-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Circle" geometry={nodes.Circle.geometry}>
          <ToonMaterial color="#b8b8b8" />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/setting-transformed.glb");
