/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 gear.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
  }
  materials: {}
}

export function Gear(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gear-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.17, 0.2, 0]} rotation={[1.58, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gear-transformed.glb')
