/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 frontend/components/models/trophy/trophy.glb --transform --types
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ToonMaterial } from "../../materials/ToonMaterial";

type GLTFResult = GLTF & {
  nodes: {
    Cube053: THREE.Mesh;
    Cube053_1: THREE.Mesh;
  };
  materials: {
    ["Silver Metal"]: THREE.MeshStandardMaterial;
    ["Color - Red Base"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Cube.016Action";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Trophy(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/trophy-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube016">
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={materials["Silver Metal"]}
          >
            <ToonMaterial color="#bf8221" />
          </mesh>
          <mesh
            name="Cube053_1"
            geometry={nodes.Cube053_1.geometry}
            material={materials["Color - Red Base"]}
          >
            <ToonMaterial color="black" />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/trophy-transformed.glb");
