/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mini_map.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_fence_simpleHigh: THREE.Mesh
    Mesh_fence_simpleHigh_1: THREE.Mesh
    Mesh_fence_simpleHigh_2: THREE.Mesh
    Mesh_fence_simpleHigh_3: THREE.Mesh
    Mesh_fence_simpleHigh_4: THREE.Mesh
    Mesh_fence_simpleHigh_5: THREE.Mesh
    Mesh_fence_simpleHigh_6: THREE.Mesh
    Mesh_fence_simpleHigh_7: THREE.Mesh
    Mesh_fence_simpleHigh_8: THREE.Mesh
    Mesh_fence_simpleHigh_9: THREE.Mesh
    Mesh_fence_simpleHigh_10: THREE.Mesh
    Mesh_fence_simpleHigh_11: THREE.Mesh
    Mesh_fence_simpleHigh_12: THREE.Mesh
    Mesh_fence_simpleHigh_13: THREE.Mesh
    Mesh_fence_simpleHigh_14: THREE.Mesh
    Mesh_fence_simpleHigh_15: THREE.Mesh
    Mesh_fence_simpleHigh_16: THREE.Mesh
    Mesh_fence_simpleHigh_17: THREE.Mesh
    Mesh_fence_simpleHigh_18: THREE.Mesh
    Mesh_fence_simpleHigh_19: THREE.Mesh
    Mesh_fence_simpleHigh_20: THREE.Mesh
    Mesh_fence_simpleHigh_21: THREE.Mesh
    Mesh_fence_simpleHigh_22: THREE.Mesh
    Mesh_fence_simpleHigh_23: THREE.Mesh
    Mesh_fence_simpleHigh_24: THREE.Mesh
    Mesh_fence_simpleHigh_25: THREE.Mesh
    Mesh_fence_simpleHigh_26: THREE.Mesh
    Mesh_fence_simpleHigh_27: THREE.Mesh
    Mesh_fence_simpleHigh_28: THREE.Mesh
    Mesh_fence_simpleHigh_29: THREE.Mesh
    Mesh_fence_simpleHigh_30: THREE.Mesh
    Mesh_fence_simpleHigh_31: THREE.Mesh
    Mesh_fence_simpleHigh_32: THREE.Mesh
    Mesh_fence_simpleHigh_33: THREE.Mesh
    Mesh_fence_simpleHigh_34: THREE.Mesh
    Mesh_fence_simpleHigh_35: THREE.Mesh
    Mesh_fence_simpleHigh_36: THREE.Mesh
    Mesh_fence_simpleHigh_37: THREE.Mesh
    Mesh_fence_simpleHigh_38: THREE.Mesh
    Mesh_fence_simpleHigh_39: THREE.Mesh
    Mesh_fence_simpleHigh_40: THREE.Mesh
    Mesh_fence_simpleHigh_41: THREE.Mesh
    Mesh_fence_simpleHigh_42: THREE.Mesh
    Mesh_fence_simpleHigh_43: THREE.Mesh
    Mesh_fence_simpleHigh_44: THREE.Mesh
    Mesh_fence_simpleHigh_45: THREE.Mesh
    Mesh_fence_simpleHigh_46: THREE.Mesh
    Mesh_fence_simpleHigh_47: THREE.Mesh
    Mesh_fence_simpleHigh_48: THREE.Mesh
    Mesh_fence_simpleHigh_49: THREE.Mesh
    Mesh_fence_simpleHigh_50: THREE.Mesh
    Mesh_fence_simpleHigh_51: THREE.Mesh
    Mesh_fence_simpleHigh_52: THREE.Mesh
    Mesh_fence_simpleHigh_53: THREE.Mesh
    Mesh_fence_simpleHigh_54: THREE.Mesh
    Mesh_fence_simpleHigh_55: THREE.Mesh
    Mesh_fence_simpleHigh_56: THREE.Mesh
    Mesh_fence_simpleHigh_57: THREE.Mesh
    Mesh_fence_simpleHigh_58: THREE.Mesh
    Mesh_fence_simpleHigh_59: THREE.Mesh
    Mesh_fence_simpleHigh_60: THREE.Mesh
    Mesh_fence_simpleHigh_61: THREE.Mesh
    Mesh_fence_simpleHigh_62: THREE.Mesh
    Mesh_fence_simpleHigh_63: THREE.Mesh
    Mesh_fence_simpleHigh_64: THREE.Mesh
    Mesh_fence_simpleHigh_65: THREE.Mesh
    Mesh_fence_simpleHigh_66: THREE.Mesh
    Mesh_fence_simpleHigh_67: THREE.Mesh
    Mesh_fence_simpleHigh_68: THREE.Mesh
    Mesh_fence_simpleHigh_69: THREE.Mesh
    Mesh_fence_simpleHigh_70: THREE.Mesh
    Mesh_fence_simpleHigh_71: THREE.Mesh
    Mesh_fence_simpleHigh_72: THREE.Mesh
    Mesh_fence_simpleHigh_73: THREE.Mesh
    Mesh_fence_simpleHigh_74: THREE.Mesh
    Mesh_fence_simpleHigh_75: THREE.Mesh
    Mesh_fence_simpleHigh_76: THREE.Mesh
    Mesh_fence_simpleHigh_77: THREE.Mesh
    Mesh_fence_simpleHigh_78: THREE.Mesh
    Mesh_fence_simpleHigh_79: THREE.Mesh
    Mesh_fence_simpleHigh_80: THREE.Mesh
    Mesh_fence_simpleHigh_81: THREE.Mesh
    Mesh_fence_simpleHigh_82: THREE.Mesh
    Mesh_fence_simpleHigh_83: THREE.Mesh
    Mesh_fence_simpleHigh_84: THREE.Mesh
    Mesh_fence_simpleHigh_85: THREE.Mesh
    Mesh_fence_simpleHigh_86: THREE.Mesh
    Mesh_fence_simpleHigh_87: THREE.Mesh
    Mesh_fence_simpleHigh_88: THREE.Mesh
    Mesh_fence_simpleHigh_89: THREE.Mesh
    Mesh_fence_simpleHigh_90: THREE.Mesh
    Mesh_fence_simpleHigh_91: THREE.Mesh
    Mesh_fence_simpleHigh_92: THREE.Mesh
    Mesh_fence_simpleHigh_93: THREE.Mesh
    Mesh_fence_simpleHigh_94: THREE.Mesh
    Mesh_fence_simpleHigh_95: THREE.Mesh
    Mesh_fence_simpleHigh_96: THREE.Mesh
    Mesh_fence_simpleHigh_97: THREE.Mesh
    Mesh_fence_simpleHigh_98: THREE.Mesh
    Mesh_fence_simpleHigh_99: THREE.Mesh
    Mesh_fence_simpleHigh_100: THREE.Mesh
    Mesh_fence_simpleHigh_101: THREE.Mesh
    Mesh_fence_simpleHigh_102: THREE.Mesh
    Mesh_fence_simpleHigh_103: THREE.Mesh
    Mesh_fence_simpleHigh_104: THREE.Mesh
    Mesh_fence_simpleHigh_105: THREE.Mesh
    Mesh_fence_simpleHigh_106: THREE.Mesh
    Mesh_fence_simpleHigh_107: THREE.Mesh
    Mesh_fence_simpleHigh_108: THREE.Mesh
    Mesh_fence_simpleHigh_109: THREE.Mesh
    Mesh_fence_simpleHigh_110: THREE.Mesh
    Mesh_fence_simpleHigh_111: THREE.Mesh
    Mesh_fence_simpleHigh_112: THREE.Mesh
    Mesh_fence_simpleHigh_113: THREE.Mesh
    Mesh_fence_simpleHigh_114: THREE.Mesh
    Mesh_fence_simpleHigh_115: THREE.Mesh
    Mesh_fence_simpleHigh_116: THREE.Mesh
    Mesh_fence_simpleHigh_117: THREE.Mesh
    Mesh_fence_simpleHigh_118: THREE.Mesh
    Mesh_fence_simpleHigh_119: THREE.Mesh
    Mesh_fence_simpleHigh_120: THREE.Mesh
    Mesh_fence_simpleHigh_121: THREE.Mesh
    Mesh_fence_simpleHigh_122: THREE.Mesh
    Mesh_fence_simpleHigh_123: THREE.Mesh
    Mesh_fence_simpleHigh_124: THREE.Mesh
    Mesh_fence_simpleHigh_125: THREE.Mesh
    Mesh_fence_simpleHigh_126: THREE.Mesh
    Mesh_fence_simpleHigh_127: THREE.Mesh
    Mesh_fence_simpleHigh_128: THREE.Mesh
    Mesh_fence_simpleHigh_129: THREE.Mesh
    Mesh_fence_simpleHigh_130: THREE.Mesh
    Mesh_fence_simpleHigh_131: THREE.Mesh
    Mesh_fence_simpleHigh_132: THREE.Mesh
    Mesh_fence_simpleHigh_133: THREE.Mesh
    Mesh_fence_simpleHigh_134: THREE.Mesh
    Mesh_fence_simpleHigh_135: THREE.Mesh
    Mesh_fence_simpleHigh_136: THREE.Mesh
    Mesh_fence_simpleHigh_137: THREE.Mesh
    Mesh_fence_simpleHigh_138: THREE.Mesh
    Mesh_fence_simpleHigh_139: THREE.Mesh
    Mesh_fence_simpleHigh_140: THREE.Mesh
    Mesh_fence_simpleHigh_141: THREE.Mesh
    Mesh_fence_simpleHigh_142: THREE.Mesh
    Mesh_fence_simpleHigh_143: THREE.Mesh
    Mesh_fence_simpleHigh_144: THREE.Mesh
    Mesh_fence_simpleHigh_145: THREE.Mesh
    Mesh_fence_simpleHigh_146: THREE.Mesh
    Mesh_fence_simpleHigh_147: THREE.Mesh
    Mesh_fence_simpleHigh_148: THREE.Mesh
    Mesh_fence_simpleHigh_149: THREE.Mesh
    Mesh_fence_simpleHigh_150: THREE.Mesh
    Mesh_fence_simpleHigh_151: THREE.Mesh
    Mesh_fence_simpleHigh_152: THREE.Mesh
    Mesh_fence_simpleHigh_153: THREE.Mesh
    Mesh_fence_simpleHigh_154: THREE.Mesh
    Mesh_fence_simpleHigh_155: THREE.Mesh
    Mesh_fence_simpleHigh_156: THREE.Mesh
    Mesh_fence_simpleHigh_157: THREE.Mesh
    Mesh_fence_simpleHigh_158: THREE.Mesh
    Mesh_fence_simpleHigh_159: THREE.Mesh
    Mesh_fence_simpleHigh_160: THREE.Mesh
    Mesh_fence_simpleHigh_161: THREE.Mesh
    Mesh_fence_simpleHigh_162: THREE.Mesh
    Mesh_fence_simpleHigh_163: THREE.Mesh
    Mesh_fence_simpleHigh_164: THREE.Mesh
    Mesh_fence_simpleHigh_165: THREE.Mesh
    Mesh_fence_simpleHigh_166: THREE.Mesh
    Mesh_fence_simpleHigh_167: THREE.Mesh
    Mesh_fence_simpleHigh_168: THREE.Mesh
    Mesh_fence_simpleHigh_169: THREE.Mesh
    Mesh_fence_simpleHigh_170: THREE.Mesh
    Mesh_fence_simpleHigh_171: THREE.Mesh
    Mesh_fence_simpleHigh_172: THREE.Mesh
    Mesh_fence_simpleHigh_173: THREE.Mesh
    Mesh_fence_simpleHigh_174: THREE.Mesh
    Mesh_fence_simpleHigh_175: THREE.Mesh
    Mesh_fence_simpleHigh_176: THREE.Mesh
    Mesh_fence_simpleHigh_177: THREE.Mesh
    Mesh_fence_simpleHigh_178: THREE.Mesh
    Mesh_fence_simpleHigh_179: THREE.Mesh
    Mesh_fence_simpleHigh_180: THREE.Mesh
    Mesh_fence_simpleHigh_181: THREE.Mesh
    Mesh_fence_simpleHigh_182: THREE.Mesh
  }
  materials: {
    ['wood.933']: THREE.MeshStandardMaterial
    ['dirt.007']: THREE.MeshStandardMaterial
    ['foliage.007']: THREE.MeshStandardMaterial
    ['dirtDark.007']: THREE.MeshStandardMaterial
    blacksquare: THREE.MeshStandardMaterial
    whitesqure: THREE.MeshStandardMaterial
  }
}

export function Mini_map(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials: gltfMaterials } = useGLTF('/mini_map-transformed.glb') as GLTFResult
  const materials = {
    ...gltfMaterials,
    ['wood.933']: new THREE.MeshToonMaterial({ color: new THREE.Color(0x704F32) }),
    ['dirt.007']: new THREE.MeshToonMaterial({ color: new THREE.Color(0x7d634a) }),
    ['foliage.007']: new THREE.MeshToonMaterial({ color: new THREE.Color(0x3e6f58) }),
    ['dirtDark.007']: new THREE.MeshToonMaterial({ color: new THREE.Color(0x594837) }),
    blacksquare: new THREE.MeshToonMaterial({ color: new THREE.Color(0x000000) }),
    whitesqure: new THREE.MeshToonMaterial({ color: new THREE.Color(0xffffff) }),
  };

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -3]}>
        <group position={[0, -2, 0.5]} scale={[2, 10, 1]}>
          <mesh geometry={nodes.Mesh_fence_simpleHigh.geometry} material={materials['wood.933']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_1.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_2.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_3.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_4.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_5.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_6.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_7.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_8.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_9.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_10.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_11.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_12.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_13.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_14.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_15.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_16.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_17.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_18.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_19.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_20.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_21.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_22.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_23.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_24.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_25.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_26.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_27.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_28.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_29.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_30.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_31.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_32.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_33.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_34.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_35.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_36.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_37.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_38.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_39.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_40.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_41.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_42.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_43.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_44.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_45.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_46.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_47.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_48.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_49.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_50.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_51.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_52.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_53.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_54.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_55.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_56.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_57.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_58.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_59.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_60.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_61.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_62.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_63.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_64.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_65.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_66.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_67.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_68.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_69.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_70.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_71.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_72.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_73.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_74.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_75.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_76.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_77.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_78.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_79.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_80.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_81.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_82.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_83.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_84.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_85.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_86.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_87.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_88.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_89.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_90.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_91.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_92.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_93.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_94.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_95.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_96.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_97.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_98.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_99.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_100.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_101.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_102.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_103.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_104.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_105.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_106.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_107.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_108.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_109.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_110.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_111.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_112.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_113.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_114.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_115.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_116.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_117.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_118.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_119.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_120.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_121.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_122.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_123.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_124.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_125.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_126.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_127.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_128.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_129.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_130.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_131.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_132.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_133.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_134.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_135.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_136.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_137.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_138.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_139.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_140.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_141.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_142.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_143.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_144.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_145.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_146.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_147.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_148.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_149.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_150.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_151.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_152.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_153.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_154.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_155.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_156.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_157.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_158.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_159.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_160.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_161.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_162.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_163.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_164.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_165.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_166.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_167.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_168.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_169.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_170.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_171.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_172.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_173.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_174.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_175.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_176.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_177.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_178.geometry} material={materials['dirt.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_179.geometry} material={materials['foliage.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_180.geometry} material={materials['dirtDark.007']} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_181.geometry} material={materials.blacksquare} />
          <mesh geometry={nodes.Mesh_fence_simpleHigh_182.geometry} material={materials.whitesqure} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mini_map-transformed.glb')
